### PR TITLE
add some more details

### PR DESCRIPTION
**Pull request by edewit**
@sebastienblanc added some more details on how to change the protocol

### CODE REVIEW

**Comment by matzew** [comment]
:+1:

On Wed, Feb 11, 2015 at 10:00 AM, Erik Jan de Wit <notifications@github.com>
wrote:

> @sebastienblanc <https://github.com/sebastienblanc> added soem more
> details on how to change the protocol
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/aerogear/aerogear-windows-oauth2/pull/6
> Commit Summary
>
>    - add some more details
>
> File Changes
>
>    - *M* README.md
>    <https://github.com/aerogear/aerogear-windows-oauth2/pull/6/files#diff-0>
>    (6)
>    - *A* protocol.png
>    <https://github.com/aerogear/aerogear-windows-oauth2/pull/6/files#diff-1>
>    (0)
>
> Patch Links:
>
>    - https://github.com/aerogear/aerogear-windows-oauth2/pull/6.patch
>    - https://github.com/aerogear/aerogear-windows-oauth2/pull/6.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/aerogear/aerogear-windows-oauth2/pull/6>.
>



-- 
Matthias Wessendorf

blog: http://matthiaswessendorf.wordpress.com/
sessions: http://www.slideshare.net/mwessendorf
twitter: http://twitter.com/mwessendorf

**Comment by sebastienblanc** [comment]
Nice ! That helps, also like we mentioned on IRC, let's specify that we have to turn on the "Drive API" on the google console.

**Comment by edewit** [comment]
@sebastienblanc added

**Comment by sebastienblanc** [comment]
:+1:

**Pull request merged**
