### PR TITLE
headers

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by matzew** [comment]
@lfryc any comments ?

**Comment by lfryc** [comment]
visually the update looks good :-)

but I'm missing instructions for building this repo, so I'm :-1:

**Comment by lfryc** [comment]
@sebastienblanc could you please try to import this project to Visual Studio and see if the project still compiles fine?

**Comment by sebastienblanc** [comment]
@lfryc I can import and compile the project in VS. Just getting this warning `C:\Users\sebi\aerogear\aerogear-windows-oauth2\aerogear-windows-oauth2\OAuth2Module.cs(63,32,63,33): warning CS0168: The variable 'e' is declared but never used`

**Comment by lfryc** [comment]
Awesome, let's merge it then in spite of the warning :-)

**Pull request merged**
